### PR TITLE
Support automatically decode v1 or v2 protocol version 

### PR DESCRIPTION
**Pull request by mattiabertorello**

### CODE REVIEW

**Comment by lxrobotics** [comment]
This works but there is no longer a need for the member variable `cloud_protocol` and there is no need to assigning it any value. As a matter of fact it could be removed including the enum class `CloudProtocol`. In any case, the two different supported protocols should be documented as comments at least on top of the parser state machine - otherwise it is hard to see from the code why this works.

**Comment by ilcato** [comment]
> This works but there is no longer a need for the member variable `cloud_protocol` and there is no need to assigning it any value. As a matter of fact it could be removed including the enum class `CloudProtocol`. In any case, the two different supported protocols should be documented as comments at least on top of the parser state machine - otherwise it is hard to see from the code why this works.

The cloud_protocol is needed in the encode process, in particular in the append method of the property class.

**Comment by mattiabertorello** [comment]
@lxrobotics I add some comments to explain the If else that now is difficult to understand.
I agree with @ilcato to leave the `cloud_protocol` as it is now and will be remove in another PR

**Comment by lxrobotics** [comment]
@ilcato That is true, I've overlooked it in the haste because I'm short on time as I've already told @mattiabertorello before I (against better knowledge) still looked at this PR ;) I know a good permanent solution and will implement on Monday morning.

**Comment by mattiabertorello** [comment]
I test it with the web-ui and the cli, It working so I think that I'm going to merge it.
On Monday you (@lxrobotics ) could implement the permanent solution

**Pull request merged**
